import { SidebarMenu } from '@nbsdev/naini-react/dist/esm/Sidebar'

const sidebarMenu: SidebarMenu[] = [
  {
    id: 'dashboard',
    type: 'link',
    icon: 'ri-dashboard-line',
    path: '/dashboard',
    label: 'Dashboard',
    active: ['/dashboard'],
  },
  {
    id: 'example',
    type: 'link',
    icon: 'ri-contract-line',
    path: '/examples',
    label: 'Example',
    active: ['/examples'],
  },
  {
    id: 'main-menu',
    type: 'divider',
    label: 'Main Menu',
  },
  {
    id: 'product',
    type: 'link',
    icon: 'ri-shopping-bag-2-line',
    path: '/product',
    label: 'Product',
  },
  {
    id: 'customer',
    type: 'link',
    icon: 'ri-group-line',
    path: '/customer',
    label: 'Customer',
  },
  {
    id: 'transaction',
    type: 'link',
    icon: 'ri-file-text-line',
    path: '/transaction',
    label: 'Transaction',
  },
  {
    id: 'statistics',
    type: 'link',
    icon: 'ri-line-chart-line',
    path: '/statistics',
    label: 'Statistics',
  },
  {
    id: 'campaign',
    type: 'link',
    icon: 'ri-user-voice-line',
    path: '/campaign',
    label: 'Campaign',
  },
  {
    id: 'log-activity',
    type: 'link',
    icon: 'ri-database-2-line',
    path: '/log-activity',
    label: 'Log Activity',
  },
  {
    id: 'other',
    type: 'divider',
    label: 'Other Menu',
  },
  {
    id: 'sub-menu-1',
    type: 'link',
    icon: 'ri-apps-line',
    label: 'Sub Menu 1',
    badge: '1',
    subMenu: [
      {
        id: 'sub-menu-1-1',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/',
        label: 'Sub Menu 1.1',
      },
      {
        id: 'sub-menu-1-2',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/',
        label: 'Sub Menu 1.2',
      },
    ],
  },
  {
    id: 'sub-menu-2',
    type: 'link',
    icon: 'ri-apps-line',
    label: 'Sub Menu 2',
    badge: '2',
    subMenu: [
      {
        id: 'sub-menu-2-1',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-2-1',
        label: 'Sub Menu 2.1',
      },
      {
        id: 'sub-menu-2-2',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-2-2',
        label: 'Sub Menu 2.2',
      },
    ],
  },
  {
    id: 'sub-menu-3',
    type: 'link',
    icon: 'ri-apps-line',
    label: 'Sub Menu 3',
    badge: '3',
    subMenu: [
      {
        id: 'sub-menu-3-1',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-3-1',
        label: 'Sub Menu 3.1',
      },
      {
        id: 'sub-menu-3-2',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-3-2',
        label: 'Sub Menu 3.2',
      },
    ],
  },
  {
    id: 'sub-menu-4',
    type: 'link',
    icon: 'ri-apps-line',
    label: 'Sub Menu 4',
    badge: '4',
    subMenu: [
      {
        id: 'sub-menu-4-1',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-4-1',
        label: 'Sub Menu 4.1',
      },
      {
        id: 'sub-menu-4-2',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-4-2',
        label: 'Sub Menu 4.2',
      },
    ],
  },
  {
    id: 'sub-menu-5',
    type: 'link',
    icon: 'ri-apps-line',
    label: 'Sub Menu 5',
    badge: '5',
    subMenu: [
      {
        id: 'sub-menu-5-1',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-5-1',
        label: 'Sub Menu 5.1',
      },
      {
        id: 'sub-menu-5-2',
        type: 'link',
        icon: 'ri-apps-line',
        path: '/sub-menu-5-2',
        label: 'Sub Menu 5.2',
      },
    ],
  },
]

export default sidebarMenu
